import 'package:flutter/material.dart';

import 'simple_input_border.dart';

/// The border, labels, icons, and styles used to decorate a [SimpleTextField].
class SimpleInputDecoration extends InputDecoration {
  const SimpleInputDecoration({
    super.icon,
    super.iconColor,
    super.label,
    super.labelText,
    super.labelStyle,
    super.floatingLabelStyle,
    super.helper,
    super.helperText,
    super.helperStyle,
    super.helperMaxLines,
    super.hintText,
    super.hintStyle,
    super.hintTextDirection,
    super.hintMaxLines,
    super.hintFadeDuration,
    super.error,
    super.errorText,
    super.errorStyle,
    super.errorMaxLines,
    super.floatingLabelBehavior,
    super.floatingLabelAlignment,
    super.isCollapsed,
    super.isDense,
    super.contentPadding,
    super.prefixIcon,
    super.prefix,
    super.prefixText,
    super.prefixStyle,
    super.prefixIconColor,
    super.prefixIconConstraints,
    super.suffixIcon,
    super.suffix,
    super.suffixText,
    super.suffixStyle,
    super.suffixIconColor,
    super.suffixIconConstraints,
    super.counter,
    super.counterText,
    super.counterStyle,
    super.filled,
    super.fillColor,
    super.focusColor,
    super.hoverColor,
    this.simpleBorder,
    super.border,
    super.errorBorder,
    super.focusedBorder,
    super.focusedErrorBorder,
    super.enabledBorder,
    super.disabledBorder,
    super.enabled,
    super.semanticCounterText,
    super.alignLabelWithHint,
    super.constraints,
  });

  /// The shape of the border to draw around the decoration's container.
  final SimpleInputBorder? simpleBorder;

  @override
  SimpleInputDecoration copyWith({
    Widget? icon,
    Color? iconColor,
    Widget? label,
    String? labelText,
    TextStyle? labelStyle,
    TextStyle? floatingLabelStyle,
    Widget? helper,
    String? helperText,
    TextStyle? helperStyle,
    int? helperMaxLines,
    String? hintText,
    TextStyle? hintStyle,
    TextDirection? hintTextDirection,
    int? hintMaxLines,
    Duration? hintFadeDuration,
    Widget? error,
    String? errorText,
    TextStyle? errorStyle,
    int? errorMaxLines,
    FloatingLabelBehavior? floatingLabelBehavior,
    FloatingLabelAlignment? floatingLabelAlignment,
    bool? isCollapsed,
    bool? isDense,
    EdgeInsetsGeometry? contentPadding,
    Widget? prefixIcon,
    Widget? prefix,
    String? prefixText,
    TextStyle? prefixStyle,
    Color? prefixIconColor,
    BoxConstraints? prefixIconConstraints,
    Widget? suffixIcon,
    Widget? suffix,
    String? suffixText,
    TextStyle? suffixStyle,
    Color? suffixIconColor,
    BoxConstraints? suffixIconConstraints,
    Widget? counter,
    String? counterText,
    TextStyle? counterStyle,
    bool? filled,
    Color? fillColor,
    Color? focusColor,
    Color? hoverColor,
    SimpleInputBorder? simpleBorder,
    InputBorder? border,
    InputBorder? errorBorder,
    InputBorder? focusedBorder,
    InputBorder? focusedErrorBorder,
    InputBorder? enabledBorder,
    InputBorder? disabledBorder,
    bool? enabled,
    String? semanticCounterText,
    bool? alignLabelWithHint,
    BoxConstraints? constraints,
  }) =>
      SimpleInputDecoration(
        icon: icon ?? this.icon,
        iconColor: iconColor ?? this.iconColor,
        label: label ?? this.label,
        labelText: labelText ?? this.labelText,
        labelStyle: labelStyle ?? this.labelStyle,
        floatingLabelStyle: floatingLabelStyle ?? this.floatingLabelStyle,
        helper: helper ?? this.helper,
        helperText: helperText ?? this.helperText,
        helperStyle: helperStyle ?? this.helperStyle,
        helperMaxLines: helperMaxLines ?? this.helperMaxLines,
        hintText: hintText ?? this.hintText,
        hintStyle: hintStyle ?? this.hintStyle,
        hintTextDirection: hintTextDirection ?? this.hintTextDirection,
        hintMaxLines: hintMaxLines ?? this.hintMaxLines,
        hintFadeDuration: hintFadeDuration ?? this.hintFadeDuration,
        error: error ?? this.error,
        errorText: errorText ?? this.errorText,
        errorStyle: errorStyle ?? this.errorStyle,
        errorMaxLines: errorMaxLines ?? this.errorMaxLines,
        floatingLabelBehavior:
            floatingLabelBehavior ?? this.floatingLabelBehavior,
        floatingLabelAlignment:
            floatingLabelAlignment ?? this.floatingLabelAlignment,
        isCollapsed: isCollapsed ?? this.isCollapsed,
        isDense: isDense ?? this.isDense,
        contentPadding: contentPadding ?? this.contentPadding,
        prefixIcon: prefixIcon ?? this.prefixIcon,
        prefix: prefix ?? this.prefix,
        prefixText: prefixText ?? this.prefixText,
        prefixStyle: prefixStyle ?? this.prefixStyle,
        prefixIconColor: prefixIconColor ?? this.prefixIconColor,
        prefixIconConstraints:
            prefixIconConstraints ?? this.prefixIconConstraints,
        suffixIcon: suffixIcon ?? this.suffixIcon,
        suffix: suffix ?? this.suffix,
        suffixText: suffixText ?? this.suffixText,
        suffixStyle: suffixStyle ?? this.suffixStyle,
        suffixIconColor: suffixIconColor ?? this.suffixIconColor,
        suffixIconConstraints:
            suffixIconConstraints ?? this.suffixIconConstraints,
        counter: counter ?? this.counter,
        counterText: counterText ?? this.counterText,
        counterStyle: counterStyle ?? this.counterStyle,
        filled: filled ?? this.filled,
        fillColor: fillColor ?? this.fillColor,
        focusColor: focusColor ?? this.focusColor,
        hoverColor: hoverColor ?? this.hoverColor,
        simpleBorder: simpleBorder ?? this.simpleBorder,
        border: border ?? this.border,
        errorBorder: errorBorder ?? this.errorBorder,
        focusedBorder: focusedBorder ?? this.focusedBorder,
        focusedErrorBorder: focusedErrorBorder ?? this.focusedErrorBorder,
        enabledBorder: enabledBorder ?? this.enabledBorder,
        disabledBorder: disabledBorder ?? this.disabledBorder,
        enabled: enabled ?? this.enabled,
        semanticCounterText: semanticCounterText ?? this.semanticCounterText,
        alignLabelWithHint: alignLabelWithHint ?? this.alignLabelWithHint,
        constraints: constraints ?? this.constraints,
      );
}
